### ISSUE TITLE
custom fields are double quoted

### ISSUE THREAD

**Issue by blynn-pbb** [TheDJVG/netbox-more-metrics#28]
When using a custom field, I'm getting a label with quotes inside quotes.  For example:
```
netbox_regions_info{__metric_label_custom_field_data__group="\"***\"",
```
> note that the custom field is type `text`

I'm using netbox regions as the object type with the following labels:
```
custom_field_data__group, name
```
Is there any way to remove the inner quotes?

**Comment by TheDJVG** [comment]
Can you share what you configured the custom field "group" as?

**Comment by TheDJVG** [comment]
Will be fixed in next release! Thanks for the report.
