### ISSUE TITLE
Expose scripts results for alerting purposes

### ISSUE THREAD

**Issue by XioNoX** [TheDJVG/netbox-more-metrics#34]
Hi,

I'm looking at replacing some of our current ad-hock python scripts that query the API and trigger Icinga alerting depending on the script/report's status. See [check_netbox_report.py](https://github.com/wikimedia/operations-puppet/blob/433ce2f70b636dad8ca5748146400f8f93dc7a36/modules/icinga/files/check_netbox_report.py)

For this I think the Prometheus exporter would be well suited but is lacking some features.

For example with the following config:
```
Metric Configuration
Name 	 	netbox_reports_results
Labels 	 	jobs__status, name
Type 	 	Gauge
Value 	 	count
Object Type 	Extras | script
Filter
{
    "jobs__data__tests__isnull": false
}
```

I get those metrics:
```
# HELP netbox_reports_results Expose results from scripts with tests results (ex reports) for alertings
# TYPE netbox_reports_results gauge
netbox_reports_results{jobs__status="completed",name="Cables"} 5.0
netbox_reports_results{jobs__status="completed",name="GetDeviceStats"} 1.0
netbox_reports_results{jobs__status="completed",name="ManagementConsole"} 2.0
netbox_reports_results{jobs__status="errored",name="ProvisionServerNetwork"} 2.0
netbox_reports_results{jobs__status="failed",name="Accounting"} 2.0
netbox_reports_results{jobs__status="failed",name="ImportPuppetDB"} 2.0
netbox_reports_results{jobs__status="failed",name="LibreNMS"} 1.0
netbox_reports_results{jobs__status="failed",name="ManagementConsole"} 1.0
netbox_reports_results{jobs__status="failed",name="PhysicalHosts"} 2.0
netbox_reports_results{jobs__status="failed",name="ProvisionServerNetwork"} 1.0
```

Here there are 2 issues.

First, the scripts named `GetDeviceStats` or `ProvisionServerNetwork` should ideally be excluded as they don't have data in their `jobs__data__tests` key, but the filter is not working as it's not `null` but it's an empty dict `{}`.
A possible solution is to implement a `exclude` dict, like you currently have `filter`, and then be able to do:
```json
{
    "jobs__data__tests": {}
}
```

Secondly, it somehow returns stats on all past execution of the scripts and not just the latest one (unlike displayed in the REST API).
See for example :
```
netbox_reports_results{jobs__status="completed",name="ManagementConsole"} 2.0
netbox_reports_results{jobs__status="failed",name="ManagementConsole"} 1.0
```
Setting the Metric type to `Info` allows to ignore the actual count, but the duplicate status are still there.
```
netbox_reports_results_info{__metric_label_jobs__status="completed",__metric_label_name="ManagementConsole"} 1.0
netbox_reports_results_info{__metric_label_jobs__status="failed",__metric_label_name="ManagementConsole"} 1.0
```
I tried to use labels such as `jobs__0__status,name` to pickup only the latest result, but that's not accepted `Labels invalid: Unsupported lookup '0' for BigAutoField or join on the field not permitted. `

I thought about exporter the job completion time as label, then filtering on the Prometheus side, but that doesn't seem optimal. Similarly with exposing the Object Type `Core | Job`.

So not sure what's the best approach here to solve this usecase while maintaining the generic aspect of your plugin.

Thanks

**Comment by TheDJVG** [comment]
While I understand the use case I don't think adding an exclude field is the right approach here. If you already know what data you want to export you should adjust the filter. For example `jobs__data__tests__has_any_keys=[<list of possible keys]`. At the same time you could make sure the producer of the data does not set the data to an empty dict.

The `data` field on the Job model in NetBox is a JSONField so you can decide how to insert data into that and make sure it makes sense.

On the second one, this plugin is supposed to be used to record timeseries, meaning you want to know the status of jobs over time. It would not make sense to only export the latest option. If you use this information for alerting you should alert if the rate of jobs failing is increasing for example.

You could also use webhooks to be notified if a jobs failed and send it directly to alertmanager (or any other tool you're using).

**Comment by XioNoX** [comment]
Thanks for your reply !

> While I understand the use case I don't think adding an exclude field is the right approach here. If you already know what data you want to export you should adjust the filter. For example jobs__data__tests__has_any_keys=[<list of possible keys]. At the same time you could make sure the producer of the data does not set the data to an empty dict.

Unfortunately `__has_any_keys` doesn't work for that usecase as the keys under `tests` are arbitrary (set for each report's tests name).
The producer here is Netbox itself, and it seems to be quite integrated to the way Scripts/Reports work (and would be a breaking change), so not sure it's best to change it there.

> On the second one, this plugin is supposed to be used to record timeseries, meaning you want to know the status of jobs over time. It would not make sense to only export the latest option. If you use this information for alerting you should alert if the rate of jobs failing is increasing for example.

It's a pretty common usecase though, see for example the classic `prometheus_node_exporter` it has the possibility to export systemd services' status:
```
node_systemd_unit_state{name="cadvisor.service",state="activating",type="simple"} 0
node_systemd_unit_state{name="cadvisor.service",state="active",type="simple"} 1
node_systemd_unit_state{name="cadvisor.service",state="deactivating",type="simple"} 0
node_systemd_unit_state{name="cadvisor.service",state="failed",type="simple"} 0
node_systemd_unit_state{name="cadvisor.service",state="inactive",type="simple"} 0
node_systemd_unit_state{name="netbox_housekeeping.service",state="activating",type="oneshot"} 0
node_systemd_unit_state{name="netbox_housekeeping.service",state="active",type="oneshot"} 0
node_systemd_unit_state{name="netbox_housekeeping.service",state="deactivating",type="oneshot"} 0
node_systemd_unit_state{name="netbox_housekeeping.service",state="failed",type="oneshot"} 0
node_systemd_unit_state{name="netbox_housekeeping.service",state="inactive",type="oneshot"} 1
[...]
```
So I think having the possibility to export reports or scripts status the same way would be very valuable.

Using webhooks to alertmanager could indeed work, but using prometheus also opens the possibility of creating dashboards for relevant reports (see for example https://grafana.wikimedia.org/d/g-AaZRFWk/systemd-status?orgId=1), and overall centralize this kind of monitoring. 

Let me know what you think !
