### ISSUE TITLE
Custom metric values based object methods

### ISSUE THREAD

**Issue by TheDJVG** [TheDJVG/netbox-more-metrics#5]
Create extended querysets and use the queries on there as metric values.

**Comment by TheDJVG** [comment]
I've not been able to create a way to mimic the `netaddr.IPSet` functionality in psql completely. I got very close but not close enough to make it useful.

I'm considering switching from the `QuerySet` approach to method on object approach (e.g. `get_utilization()` on the `ipam.Prefix` model that NetBox already uses.

**Comment by TheDJVG** [comment]
Implemented a new method that's using object methods instead of the ORM directly. Example use for rack utilization:
![image](https://user-images.githubusercontent.com/17107225/221339158-7141d4b4-ddcc-4163-8d6f-77c2289b69ba.png)

**Comment by nikolasj** [comment]
@TheDJVG, hi! When can we expect a new version with get_utilization()?

**Comment by TheDJVG** [comment]
Hi @nikolasj, thanks for reaching out. I'm still contemplating if this is the right way. But happy to release now and refactor later if needed.

**Comment by nikolasj** [comment]
I need this feature

**Comment by TheDJVG** [comment]
0.2.0 has just been released and is available on pypi.

**Comment by nikolasj** [comment]
Hi, @TheDJVG
I have a problem 
```
ERROR: Could not find a version that satisfies the requirement netbox-more-metrics==0.2.0 (from versions: 0.1.0, 0.1.1)
```

**Comment by TheDJVG** [comment]
This looks more related to the way you managed your packages. Also make sure you create a new issue with appropriate information when it's not working.

Pypi works as expected:
```bash
$ pip download netbox-more-metrics==0.2.0 -d /tmp                                                                                                            ✔ 
Collecting netbox-more-metrics==0.2.0
  Using cached netbox_more_metrics-0.2.0-py3-none-any.whl (17 kB)
Collecting prometheus-client>=0.12.0
  Using cached prometheus_client-0.16.0-py3-none-any.whl (122 kB)
Saved /tmp/netbox_more_metrics-0.2.0-py3-none-any.whl
Saved /tmp/prometheus_client-0.16.0-py3-none-any.whl
Successfully downloaded netbox-more-metrics prometheus-client
```
