### ISSUE TITLE
Rename labels

### ISSUE THREAD

**Issue by TheDJVG** [TheDJVG/netbox-more-metrics#9]
It might be useful to rename labels.

In this example it's clear that you use`site__name` to add the name as a label, you might want to just have `site` instead:
![image](https://user-images.githubusercontent.com/17107225/221504800-61291737-a1c8-4d65-95f4-0c88df0ac23c.png)

Would be nice to create a relabel configuration so that you map any source label to different name.

**Comment by XioNoX** [comment]
Hi, that feature would be very useful to us !
We curently use a customscript to generate those metrics, which is less than ideal :)
Our code uses standardized labels that we use across all our monitoring, for example:
`netbox_device_count{status="active",datacenter="eqiad",rackgroup="eqiad-row-a",manufacturer="dell"} 185`

However the equivalent using this plugin is less user friendly:
`netbox_device_count{device_type__manufacturer__slug="dell",rack__location__slug="eqiad-row-a",site__slug="eqiad",status="active"} 185.0`

Thanks

**Comment by TheDJVG** [comment]
The question would be how this would work, a manual rename would be quite cumbersome. On the other hand the reference object type name might be used (e.g. `site`) however, how to deal in a situation where multiple labels are referencing the same related field? 

For example what if you want to expose the `name` and `slug` of a `manufacturer`?

**Comment by XioNoX** [comment]
"easiest" I think would be to be able to define a `dict` with old:new name. For example in my case above:
```python
{
'device_type__manufacturer__slug': 'manufacturer',
'rack__location__slug': 'rackgroup',
'site__slug', 'datacenter',
}
```
Then do a "basic" replace. Putting quotes as I don't know how complex it can really be :)
Maybe with some safeguards to make sure the new labels are unique.
Let me know what you think !

**Comment by TheDJVG** [comment]
That might work from a initial implementation but it's not very intuitive, at the same time the filter can be already tough to understand so it might not be a big problem. 

I was more thinking how this could be exposed nicely in the UI, but that could be an iteration.

**Comment by XioNoX** [comment]
Indeed, as long as the data structure is good, the UI can be step 2 :)
Especially as this plugin seems to be aimed at power-users that are not scared to define a dict in the UI, like the filters.

**Comment by TheDJVG** [comment]
Pushed some changes to to make this work.

Renaming would look like this:
![image](https://github.com/user-attachments/assets/d80d8040-7ebe-4ef4-9ac4-17d8212a631e)
![image](https://github.com/user-attachments/assets/18903641-8d90-411b-892a-6a2d3a8a987e)

The validators should prevent duplicate labels or shadowing of original labels:
![image](https://github.com/user-attachments/assets/7790f95e-dd1e-4e6c-84e3-bc2b97e65a52)
![image](https://github.com/user-attachments/assets/8dd0da14-762a-4e48-b7a1-6859d65bc2b1)

**Comment by XioNoX** [comment]
Awesome, thanks for the quick turnaround !
